"""
Report generation — produces PDF and Excel reports with charts and data tables.
Saves to ~/Desktop/jarvis_reports/.
"""
import os
import time
from pathlib import Path

REPORTS_DIR = os.path.expanduser("~/Desktop/jarvis_reports")


def _ensure_dir():
    os.makedirs(REPORTS_DIR, exist_ok=True)


def generate_report(
    title: str,
    sections: list,
    output_format: str = "pdf",
    output_path: str = None,
    data_path: str = None,
) -> str:
    """
    Generate a report.

    sections: list of dicts — each has 'heading' and 'content' (text, table, or chart path)
    output_format: 'pdf' | 'excel' | 'html'
    data_path: optional CSV/Excel file to auto-generate data section from

    Returns the path of the generated report file.
    """
    _ensure_dir()
    fmt = output_format.lower().strip()

    ts = int(time.time())
    safe_title = title.replace(" ", "_").replace("/", "-")

    if fmt == "excel":
        return _generate_excel(title, sections, data_path, output_path, safe_title, ts)
    elif fmt == "html":
        return _generate_html(title, sections, data_path, output_path, safe_title, ts)
    else:  # pdf (via HTML → PDF or fallback to HTML)
        return _generate_pdf(title, sections, data_path, output_path, safe_title, ts)


def _section_html(section: dict) -> str:
    heading = section.get("heading", "")
    content = section.get("content", "")
    chart = section.get("chart", "")

    html = ""
    if heading:
        html += f"<h2>{heading}</h2>\n"
    if content:
        html += f"<p>{content.replace(chr(10), '<br>')}</p>\n"
    if chart and os.path.exists(chart):
        html += f'<img src="file://{chart}" style="max-width:100%;margin:12px 0;border:1px solid #00FFFF44;">\n'
    return html


def _build_html(title: str, sections: list, data_path: str = None) -> str:
    data_section = ""
    if data_path:
        try:
            from control.analyst import analyze_data
            analysis = analyze_data(data_path)
            data_section = f"<h2>Data Analysis</h2><pre style='font-size:11px'>{analysis}</pre>"
        except Exception as e:
            data_section = f"<p>Could not load data: {e}</p>"

    sections_html = "\n".join(_section_html(s) for s in sections)

    from datetime import datetime
    date_str = datetime.now().strftime("%B %d, %Y")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap');
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      background: #080f14;
      color: #e0e0e0;
      font-family: 'Share Tech Mono', 'Courier New', monospace;
      padding: 48px;
      max-width: 900px;
      margin: 0 auto;
    }}
    header {{
      border-bottom: 1px solid #00FFFF44;
      padding-bottom: 24px;
      margin-bottom: 32px;
    }}
    h1 {{
      font-size: 24px;
      color: #00FFFF;
      letter-spacing: 4px;
      text-transform: uppercase;
    }}
    .meta {{
      font-size: 10px;
      color: #00FFFF88;
      letter-spacing: 2px;
      margin-top: 6px;
    }}
    h2 {{
      font-size: 13px;
      color: #00FFFF;
      letter-spacing: 3px;
      text-transform: uppercase;
      margin: 32px 0 12px;
      border-left: 2px solid #00FFFF;
      padding-left: 10px;
    }}
    p {{
      font-size: 12px;
      line-height: 1.7;
      color: #c0c0c0;
      margin-bottom: 12px;
    }}
    pre {{
      background: #0a1520;
      border: 1px solid #00FFFF22;
      padding: 14px;
      font-size: 10px;
      line-height: 1.5;
      overflow-x: auto;
      color: #a0c0d0;
      margin: 12px 0;
    }}
    table {{
      width: 100%;
      border-collapse: collapse;
      font-size: 11px;
      margin: 12px 0;
    }}
    th {{
      background: #0a1520;
      color: #00FFFF;
      padding: 8px 12px;
      text-align: left;
      border: 1px solid #00FFFF22;
      letter-spacing: 1px;
      font-size: 10px;
    }}
    td {{
      padding: 7px 12px;
      border: 1px solid #ffffff11;
      color: #c0c0c0;
    }}
    tr:nth-child(even) {{ background: #0a1520; }}
    footer {{
      margin-top: 48px;
      padding-top: 16px;
      border-top: 1px solid #00FFFF22;
      font-size: 9px;
      color: #00FFFF55;
      letter-spacing: 2px;
    }}
  </style>
</head>
<body>
  <header>
    <h1>{title}</h1>
    <div class="meta">NEXEL INTELLIGENCE PLATFORM · {date_str} · JARVIS</div>
  </header>

  {sections_html}
  {data_section}

  <footer>GENERATED BY JARVIS — NEXEL INTELLIGENCE PLATFORM — CONFIDENTIAL</footer>
</body>
</html>"""


def _generate_html(title, sections, data_path, output_path, safe_title, ts) -> str:
    html = _build_html(title, sections, data_path)
    path = output_path or os.path.join(REPORTS_DIR, f"{safe_title}_{ts}.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    return path


def _generate_pdf(title, sections, data_path, output_path, safe_title, ts) -> str:
    """Generate PDF using reportlab."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
        from reportlab.lib.enums import TA_LEFT

        path = output_path or os.path.join(REPORTS_DIR, f"{safe_title}_{ts}.pdf")

        BG = colors.HexColor("#080f14")
        CYAN = colors.HexColor("#00FFFF")
        DIM = colors.HexColor("#c0c0c0")
        MONO = "Courier"

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle("JTitle", fontName=MONO, fontSize=18,
                                     textColor=CYAN, spaceAfter=6, leading=22)
        meta_style = ParagraphStyle("JMeta", fontName=MONO, fontSize=8,
                                    textColor=colors.HexColor("#00FFFF88"), spaceAfter=20)
        h2_style = ParagraphStyle("JH2", fontName=MONO, fontSize=11,
                                  textColor=CYAN, spaceBefore=20, spaceAfter=8, leading=16)
        body_style = ParagraphStyle("JBody", fontName=MONO, fontSize=9,
                                    textColor=DIM, leading=14, spaceAfter=8)
        code_style = ParagraphStyle("JCode", fontName=MONO, fontSize=7,
                                    textColor=colors.HexColor("#a0c0d0"),
                                    backColor=colors.HexColor("#0a1520"),
                                    borderPad=6, leading=11, spaceAfter=10)

        from datetime import datetime
        date_str = datetime.now().strftime("%B %d, %Y")

        story = []
        story.append(Paragraph(title.upper(), title_style))
        story.append(Paragraph(f"NEXEL INTELLIGENCE PLATFORM · {date_str} · JARVIS", meta_style))
        story.append(Spacer(1, 0.1 * inch))

        for section in sections:
            heading = section.get("heading", "")
            content = section.get("content", "")
            chart = section.get("chart", "")

            if heading:
                story.append(Paragraph(heading.upper(), h2_style))
            if content:
                for line in content.split("\n"):
                    if line.strip():
                        story.append(Paragraph(line, body_style))
            if chart and os.path.exists(chart):
                try:
                    img = RLImage(chart, width=5 * inch, height=2.8 * inch)
                    story.append(img)
                    story.append(Spacer(1, 0.1 * inch))
                except Exception:
                    pass

        if data_path:
            try:
                from control.analyst import analyze_data
                analysis = analyze_data(data_path)
                story.append(Paragraph("DATA ANALYSIS", h2_style))
                story.append(Paragraph(analysis[:3000], code_style))
            except Exception:
                pass

        doc = SimpleDocTemplate(
            path,
            pagesize=letter,
            leftMargin=0.75 * inch,
            rightMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
        )
        doc.build(story)
        return path

    except ImportError:
        # Fallback to HTML
        html_path = _generate_html(title, sections, data_path, None, safe_title, ts)
        return f"reportlab not available — generated HTML instead: {html_path}"
    except Exception as e:
        return f"PDF generation error: {e}"


def _generate_excel(title, sections, data_path, output_path, safe_title, ts) -> str:
    """Generate Excel report with data and summary sheets."""
    try:
        import openpyxl
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
        from openpyxl.utils import get_column_letter

        path = output_path or os.path.join(REPORTS_DIR, f"{safe_title}_{ts}.xlsx")
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Report"

        # Styles
        hdr_font = Font(name="Courier New", bold=True, color="00FFFF", size=11)
        title_font = Font(name="Courier New", bold=True, color="00FFFF", size=14)
        body_font = Font(name="Courier New", color="C0C0C0", size=9)
        bg_fill = PatternFill("solid", fgColor="080F14")
        hdr_fill = PatternFill("solid", fgColor="0A1520")

        # Title
        ws.merge_cells("A1:D1")
        cell = ws["A1"]
        cell.value = title.upper()
        cell.font = title_font
        cell.fill = bg_fill
        cell.alignment = Alignment(horizontal="left")
        ws.row_dimensions[1].height = 28

        row = 3
        for section in sections:
            heading = section.get("heading", "")
            content = section.get("content", "")
            if heading:
                ws.cell(row=row, column=1, value=heading.upper()).font = Font(name="Courier New", bold=True, color="00FFFF", size=10)
                ws.cell(row=row, column=1).fill = hdr_fill
                row += 1
            if content:
                for line in content.split("\n"):
                    c = ws.cell(row=row, column=1, value=line)
                    c.font = body_font
                    c.fill = bg_fill
                    row += 1
            row += 1

        # Data sheet
        if data_path:
            from control.analyst import _load_dataframe
            df, err = _load_dataframe(data_path)
            if df is not None:
                ws2 = wb.create_sheet("Data")
                for j, col in enumerate(df.columns, 1):
                    c = ws2.cell(row=1, column=j, value=col)
                    c.font = hdr_font
                    c.fill = hdr_fill
                for i, row_data in enumerate(df.head(1000).values, 2):
                    for j, val in enumerate(row_data, 1):
                        c = ws2.cell(row=i, column=j, value=val)
                        c.font = body_font
                        c.fill = bg_fill

        wb.save(path)
        return path

    except ImportError:
        return "openpyxl not installed. Run: pip install openpyxl"
    except Exception as e:
        return f"Excel generation error: {e}"
